"""refactor: remove unused phone column from employees

Revision ID: 88ee77d3f180
Revises: ee4f36e3509c
Create Date: 2026-01-26 10:08:28.661736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88ee77d3f180'
down_revision = 'ee4f36e3509c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
