"""feat: initial schema with employees surveys and responses

Revision ID: 8a6fd62aa350
Revises: 
Create Date: 2026-01-24 16:03:59.306189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a6fd62aa350'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_name'), ['name'], unique=True)

    op.create_table('surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('surveys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_surveys_date'), ['date'], unique=False)

    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('corporate_email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('function', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('tenure', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('generation', sa.String(length=50), nullable=True),
    sa.Column('company_level_0', sa.String(length=100), nullable=True),
    sa.Column('directorate_level_1', sa.String(length=100), nullable=True),
    sa.Column('management_level_2', sa.String(length=100), nullable=True),
    sa.Column('coordination_level_3', sa.String(length=100), nullable=True),
    sa.Column('area_level_4', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_email'), ['email'], unique=True)

    op.create_table('responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('role_interest', sa.Integer(), nullable=True),
    sa.Column('contribution', sa.Integer(), nullable=True),
    sa.Column('learning', sa.Integer(), nullable=True),
    sa.Column('feedback_score', sa.Integer(), nullable=True),
    sa.Column('manager_interaction', sa.Integer(), nullable=True),
    sa.Column('career_clarity', sa.Integer(), nullable=True),
    sa.Column('permanence', sa.Integer(), nullable=True),
    sa.Column('enps', sa.Integer(), nullable=True),
    sa.Column('role_interest_comment', sa.Text(), nullable=True),
    sa.Column('contribution_comment', sa.Text(), nullable=True),
    sa.Column('learning_comment', sa.Text(), nullable=True),
    sa.Column('feedback_comment', sa.Text(), nullable=True),
    sa.Column('manager_interaction_comment', sa.Text(), nullable=True),
    sa.Column('career_clarity_comment', sa.Text(), nullable=True),
    sa.Column('permanence_comment', sa.Text(), nullable=True),
    sa.Column('enps_comment', sa.Text(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('sentiment_label', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_responses_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_responses_sentiment_label'), ['sentiment_label'], unique=False)
        batch_op.create_index(batch_op.f('ix_responses_survey_id'), ['survey_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_responses_survey_id'))
        batch_op.drop_index(batch_op.f('ix_responses_sentiment_label'))
        batch_op.drop_index(batch_op.f('ix_responses_employee_id'))

    op.drop_table('responses')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_email'))
        batch_op.drop_index(batch_op.f('ix_employees_department_id'))

    op.drop_table('employees')
    with op.batch_alter_table('surveys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_surveys_date'))

    op.drop_table('surveys')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_name'))

    op.drop_table('departments')
    # ### end Alembic commands ###
