"""refactor: add response_sentiments table for granular ai analysis

Revision ID: dfe5adc4a301
Revises: 8a6fd62aa350
Create Date: 2026-01-24 16:13:25.562219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfe5adc4a301'
down_revision = '8a6fd62aa350'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response_sentiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('sentiment_label', sa.String(length=20), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['response_id'], ['responses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('response_sentiments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_response_sentiments_response_id'), ['response_id'], unique=False)

    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_responses_sentiment_label'))
        batch_op.drop_column('sentiment_score')
        batch_op.drop_column('sentiment_label')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sentiment_label', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sentiment_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_responses_sentiment_label'), ['sentiment_label'], unique=False)

    with op.batch_alter_table('response_sentiments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_response_sentiments_response_id'))

    op.drop_table('response_sentiments')
    # ### end Alembic commands ###
