"""refactor: add ordinal columns tenure_rank and sentiment_rating

Revision ID: ee4f36e3509c
Revises: dfe5adc4a301
Create Date: 2026-01-25 08:43:20.653368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee4f36e3509c'
down_revision = 'dfe5adc4a301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenure_rank', sa.Integer(), nullable=True))

    with op.batch_alter_table('response_sentiments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sentiment_rating', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response_sentiments', schema=None) as batch_op:
        batch_op.drop_column('sentiment_rating')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('tenure_rank')

    # ### end Alembic commands ###
